name: Build Check

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up Go 1.21.5
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
        id: go


      - name: mod tidy
        run: go mod tidy -v

      - name: check basic
        run: cd examples/basic;windres -i ui/ui.rc -O coff -o ui.syso

      - name: build basic
        run: cd examples/basic;go generate -v;go build -ldflags="-s -w -H windowsgui" -v

      - name: check simple
        run:
          cd examples/simple;
          windres -i emptyProject/Debug/resource.res -O coff -o vsui.syso;
          go build -ldflags="-s -w -H windowsgui"

# 取消 winres调用。 生成的资源文件会变成乱码，暂时不知道如果解决。 发布 wowjump release之前需要手动生成 ui.syso.
# windres -i ui/ui.rc -O coff -o ui.syso;
      - name: check wowjump
        run:
          cd examples/wowjump;
          go generate;
          go build -ldflags="-s -w -H windowsgui"

      - name: Pre-release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'whtiehack/wingui'
        run: |
          mkdir release
          Compress-Archive -CompressionLevel Optimal -Force -Path examples/basic/basic.exe,examples/basic/bitmap.jpg -DestinationPath release/basic.zip
          Compress-Archive -CompressionLevel Optimal -Force -Path examples/simple/simple.exe -DestinationPath release/simple.zip
          Compress-Archive -CompressionLevel Optimal -Force -Path examples/wowjump/wowjump.exe -DestinationPath release/wowjump.zip

      - name: Draft Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'whtiehack/wingui'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release/basic.zip
            release/simple.zip
            release/wowjump.zip
          draft: true